### ISSUE TITLE
(Wrong) Clustering leads to zero-length reconstructed track 

### ISSUE THREAD

**Issue by matteoceschia** [SuperNEMO-DBD/Falaise#128]
I ran flreconstruct with the official reconstruction module (see attached .txt) on a 1M Se82.0nu sample and I came across a clearly misreconstructed event (see attached .png).
Two clearly distinct tracks are clustered into a single cluster (in blue). This causes the reconstructed track to have the initial and final vertices at the same position (circle bottom right), so the track has zero length, which makes sensitivity module fail when it is run on the file. The reconstructed track also has very high chi2 per degrees of freedom.

As Chreyl pointed out, this poses several issues, of varying severity:

1) The clusterer has clustered all the blue hits together, which is a strange choice, but shouldn't cause such a serious failure at the next step.

2) The track fitter has somehow decided that the best fit to this messy cluster is a zero-length track, which it should not be allowed to do. (most serious issue)

3) Sensitivity module crashes on zero-length tracks, which we can and should fix, but also - it should never be getting a zero-length track to analyse.

[official_conf.txt](https://github.com/SuperNEMO-DBD/Falaise/files/2873958/official_conf.txt)

<img width="1093" alt="problematic_event" src="https://user-images.githubusercontent.com/43614047/52926387-702c3100-332d-11e9-972a-92ab9f9032a9.png">

**Comment by yramachers** [comment]
I would simply called that a failed reconstruction. It either went wrong due to an assumption in the TrackFit module or the ParticleTracking module. Listing 3 unassociated calo hits as well as three particles (tracks with associated calo) looks a bit strange too. The clustering does make sense assuming a bouncing electron, foil, calo, foil. Ideally that would be broken into two which would then result in two tracks being fitted. Anyway, protect the sensitivity module against breaking on zero length tracks and simply count those cases as failed reconstruction events.
Little else to do there for us at this stage.

**Comment by drbenmorgan** [comment]
Closing as it appears discussion has finished/resolved the issue.
