### ISSUE TITLE
Cut module

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#177]
Revisiting an issue we've talked about for a while - the idea of a cuts module. It would be great to be able to produce trimmed brio files containing only a subset of events - either from a list of event numbers, and/or by cutting on some parameter or combination of parameters from the brio files themselves. With more time on our hands at the moment - how viable is it to look at this and what would we need for someone to get started?

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, I had a *very* quick look this afternoon, and I think this is mostly straightforward though may need some scaffolding in Falaise.

Modules can return a status that says "don't process this event any further", so that's the basic true/false selection already there. I need to check what the pipeline then does with the event, as I have a feeling it may still write the event out. There's some functionality in Bayeux for "paths" in pipelines, so I can likely adapt something from that. Would an initial functionality of "if passes cut process further, else send to the void" be sufficient"?

Can do this through #163 as that's the same topic!

**Comment by cherylepatrick** [comment]
Just realised I didn't answer this, but yes! But we probably want to retain event numbers if possible so we can match back to an original source.

**Comment by cherylepatrick** [comment]
We'd let this slip, but I'm bumping this now as it would be particularly useful for @wausain 's  current analysis, where he's made something like 11 million events for the Tl208  external background from the PMT's and is interested in 25 of them. Suggestion is that it is maybe not too bad to get this going? What do we need to do to make it happen?

**Comment by drbenmorgan** [comment]
Hi @cherylepatrick, @wausain, I've drafted a rough outline of how a cut (I've called it "filter" for now to match Art/LArSoft) module could work with needed C++ and scripting in #163. Please have a look and let me know what you think!

**Comment by drbenmorgan** [comment]
Resolved by #163
