### ISSUE TITLE
Make test 71, Issue 201 fix, failure

### ISSUE THREAD

**Issue by willquinn** [SuperNEMO-DBD/Falaise#225]
Building the current version of the Falaise develop branch succeeds on CCLyon - simulation and reconstruction work correctly as seen through flvisualise. However `$ make test` shows a single failure on test 71 of the many tests. Relevant information:

[info] load_boost_1_69_0_setup: BOOST version 1.69.0 is now setup !
[info] load_camp_0_8_4_setup: CAMP version 0.8.4 is now setup !
[info] load_gsl_2_4_setup: GSL version 2.4 is now setup !
[info] load_clhep_2_1_3_1_setup: CLHEP version 2.1.3.1 is now setup !
[info] load_root_6_16_00_setup: ROOT version 6.16.00 is now setup !
[info] load_g4datasets_9_6_4_setup: Geant4 datasets version 9.6.4 is now setup !
[info] load_xercesc_3_2_3_setup: XERCESC version 3.2.3 is now setup !
[info] load_doxygen_1_8_18_setup: DOXYGEN version 1.8.18 is now setup !
[info] load_geant4_9_6_4_setup: GEANT4 version 9.6.4 is now setup !
[info] load_bxdecay0_dev_setup: BXDECAY0 version 1.0.5 is now setup !
[info] load_bayeux_3_4_2_setup: Bayeux version 3.4.2 is now setup !
[info] load_sncabling_1_0_1_setup: SNCABLING version 1.0.1 is now setup !
[info] load_snfee_pro_setup: SNFEE version 0.2.4-alpha is now setup !
[info] load_falaise_devel_setup: Falaise version devel is now setup !

output of the command `ctest -VV -I 71,71`:
[test_output.log](https://github.com/SuperNEMO-DBD/Falaise/files/5888879/test_output.log)

The issue that was resolved:
#201

**Comment by drbenmorgan** [comment]
I've finally had some time to look at this. What seems to be causing this is that the Lyon system is using a different Bayeux version, and that uses the `bxdecay0` generator instead of the builtin `genbb_help`. Building Bayeux 3.4.2 with/out `bxdecay0` results in the test failing/passing (and failing with the same numbers above), so it's reproducible.

I don't think this is a bug, rather reflects a currently untested configuration. To confirm that, I'd suggest checking that the output from `flsimulate` generated in the test looks reasonable (simply dumping the output using `flreconstruct` should suffice).

**Comment by drbenmorgan** [comment]
Confirmed as due to use of newer Bayeux/bxdecay0, not a bug, just reflects changes to random number seeding. Will confirm update needed to test on upgrade to supported Bayeux version.
