### ISSUE TITLE
Long list of new vertex generators is long

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/Falaise#233]
Small request/question relating to the very nice enhancements in #231.

With the realistic foils, we now have a lot of new vertex generators (each foil and pad's bulk and surface can be selected individually). That's great and I understand where it will be useful, so thank you! However - it now means that the list of generators  in `flsimulate-configure `is very long, and (especially over the ssh link to CCLyon) it can be quite slow to scroll past them all to get to other generators that might be used more frequently. Is there anything we can do about that?
I wondered if maybe we could move these more obscure generators to an additional "extended" list (maybe you have to tick an extra box to expand it, or something? Or at the very least, could the extra ones (the individual foils/pads) be at the very end of the list, so that you don't have to scroll past them to get to the others? 

I totally understand that this isn't a bug - but if it's easy to change, it might make life easier for users. What do you think?

**Comment by fmauger** [comment]
Hi
Not easy to implement and implies some work/investigation with Qt GUI features in Bayeux (with some kind of guided spliting of a main menu to smart submenus). I'll think about it for I know the large amount of choices is not easy to address now on the screen...

**Comment by cherylepatrick** [comment]
Thank you! It's not a huge problem at all - better too much choice than not enough!

**Comment by lemiere** [comment]
We can provide a 'short' VG list for standard users
* uniform full foil surface
* uniform full foil bulk
* Se82 full foil bulk
The advance user will have to fill the conf file by hand or to generate the full .csv file.

Make sense ?

**Comment by cherylepatrick** [comment]
To me that makes lots of sense as long as we make sure that the documentation for how to generate simulation has a link to how to do it the manual way, and the names of the "advanced" configs to pick from. @willquinn and I could perhaps sort that out, although I think @lemiere  or @fmauger would probably need to check it to make sure we got it right...

**Comment by lemiere** [comment]
Try and if only few VG are available, you succeeded ! ;-)

**Comment by willquinn** [comment]
The file we need is this: `resources/snemo/demonstrator/geometry/variants/vertex/vertexes_generators.csv` perhaps we create an advanced version and a user version

**Comment by fmauger** [comment]
I consider the option of having two CSV files (basic vs advanced) is probably the cheapest solution to implement.
In that case, that would imply to set a specific CMake OPTION in Falaise like this:

`option(FALAISE_WITH_ADVANCED_SOURCE_VG "Provide a looooong list of source  ertex generators" OFF)`

and install the proper CSV file in the config tree as needed (using some conditional  CMake `copy` or `configure_file` and `install ` directives... or something like that)

The name of the installed CSV file (the short "basic" or the "long" advanced version) should not be changed in the variant system for that would minimize efforts.

The counterpart is that when installed without this option, the "atomic" VG are not available at all.
Probably this is not a big pb so that interested users can easily install both versions on their system, depending on the needs.

**Comment by cherylepatrick** [comment]
@fmauger you read my mind! I was just going to suggest the two files. However I wondered - do we have to recompile to make the choice? Or is there a possibility to add a command line switch to flsimulate-configure to tell it to read the list from the advanced file instead of the default shorter one?  Not sure if that's a question for you or @drbenmorgan ...

**Comment by drbenmorgan** [comment]
@cherylepatrick, an option to `flsimulate-configure` would be the best solution if that's possible within the config/variant system (to which I defer to @fmauger). 

Otherwise, I don't have an opinion on the proposals other than **they be documented, and done so clearly in the Doxygen docs**. Even if the "advanced" generators are likely to be used mostly for production runs, it should still be clearly written down what and how to activate/use them.

**Comment by fmauger** [comment]
The new PR 237 and the one comming soon related to issue 241 + bump to Bayeux 3.5.1 will solve this issue in principle.

**Comment by fmauger** [comment]
The feature for short list of VG is implemented in Falaise now.
