### ISSUE TITLE
Implement custom magnetic field mapping in flsimulate

### ISSUE THREAD

**Issue by wausain** [SuperNEMO-DBD/Falaise#86]
Within the falaise software I found the option of adding a mapped field to the simulation configuration file and there was an example mapping 'Map0' present. 

I looked at the mapping files but cannot figure out how they work and  how they can be implemented. I can run the simulation with the Map0 file but would like to create my own mapping files to test but am unsure as to how.

**Comment by fmauger** [comment]
Bayeux provides only the basic interface to declare/instantiate EM field objects of simple types:
`emfield::uniform_magnetic_field`, `emfield::oscillating_field`,  `emfield::linear_combination_field`,
`emfied::multi_zone_field`...
There is no native support for mapped/interpolated fields so far, because there is no
standard format for E/B map files to be parsed before usage.
The solution in Falaise is to provide the `snemo::geometry::mapped_magnetic_field` class which is
specialized to load the home-made B-map ASCII/CSV files as provided by Steve Snow with its original
Python software. For now it is the only *B-map* format supported in Falaise (it refers to the
so-called `MM_IMPORT_CSV_MAP_0` mapping mode). Should other B-map formats be used by collaborators in the future,
we will explicitely add additional modes to support them.

At least, the good news is that if you are able to provide your B-map in Steve's format, you can then ask Falaise
to load this file from the variant system, in place of the default
"@falaise:config/snemo/demonstrator/geometry/4.0/plugins/magnetic_field/data/csv_map_0/MapSmoothPlusDetail.csv" file
provided by Steve. It should work, picking up a point in space and interpolating the (Bx,By,Bz) coordinates of
your modelled field.

Important remarks about the `MM_IMPORT_CSV_MAP_0` mapping mode:
---------------------------------------------------------------

To model the magnetic field within the SuperNEMO geometry, Steve uses a coordinates system which
is not the same as the one used by the SuperNEMO geometry:

SuperNEMO/Falaise | Steve's B-map
------------------------------- | ------------------------
x  | z
y  | x
z  | y
Bx | Bz
By | Bx
Bz | By

The `snemo::geometry::mapped_magnetic_field`  class performs the proper transformations
while computing the B-field at each step during Geant4 based particle tracking. However depending
on how you have generated your B-map, you must use Steve's system to store the value in the map.

Also the file contains only the fully symmetrical map with respect to the detector's origin (0.0,0.0,0,0):
so that the (Bx, By, Bz) coordinates are stored only for the region of the 3D space bounded by half-axis
for all directions X (x>=0), Y (y>=0) and Z (z>=0).


Detailed format of the `MaspSmoothPlusDetail.csv` file:
-------------------------------------------------------

How to read the B-map format provided by Steve and parsed and used by the `snemo::geometry::mapped_magnetic_field` class:
* The first line corresponds to the B-map header:
~~~
nx,ny,nz,Ox,Oy,Oz,dx, dy, dz
~~~
   where:
     - nx=141,ny=96,nz=24 are the numbers of regular sampling steps respectivly on the X, Y and Z axis (Steve's system of coordinates),
     - Ox=0.0,Oy=0.0,Oz=0.0 are the coordinates of the origin,
     - dx=0.02,dy=0.02,dz=0.02 (m) are the width of the sampling steps respectivly on the X, Y and Z axis.
* The other following lines contain the B-map records organized by non-bounded blocks:
	 - There is one record per line
     - Each line has a header of 3 integers:
	   * ax: index of the B vector's coordinates on X (ax=0), Y (ax=1) or Z (ax=2),
	   * iy: positional sampling index on the Y axis (iy=[0,ny[),
	   * iz: positional sampling index on the Z axis (iz=[0,nz[))
	   Then  this short header is followed
	   by the values of the B vector's coordinate for each positional sampling index on the X axis.

As an illustration, the following sample adds unsupported comments for a better separation of blocks
of records:
~~~
### Start the Bx block (ax=0) with nz blocks of ny records
# first block of ny lines of nx values for iz=0
ax=0 iy=0    iz=0    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
ax=0 iy=1    iz=0    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
ax=0 iy=2    iz=0    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
.
.
.
ax=0 iy=ny-1 iz=0    Bx[0,iy=ny-1,iz]      Bx[1,iy=ny-1,0]       Bx[2,iy=ny-1,iz]     ... Bx[nx-1,iy=ny-1,iz]
# second block of ny lines of nx values for iz=1
ax=0 iy=0    iz=1    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
ax=0 iy=1    iz=1    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
ax=0 iy=2    iz=1    Bx[0,iy,iz]           Bx[1,iy,iz]           Bx[2,iy,iz]          ... Bx[nx-1,iy,iz]
.
.
.
ax=0 iy=ny-1 iz=1    Bx[0,iy=ny-1,iz]      Bx[1,iy=ny-1,iz]      Bx[2,iy=ny-1,iz]     ... Bx[nx-1,iy=ny-1,iz]
...
# last block of ny lines of nx values for iz=nz-1
ax=0 iy=0    iz=nz-1 Bx[0,iy,iz=nz-1]      Bx[1,iy,iz=nz-1]      Bx[2,iy,iz=nz-1]     ... Bx[nx-1,iy,iz=nz-1]
ax=0 iy=1    iz=nz-1 Bx[0,iy,iz=nz-1]      Bx[1,iy,iz=nz-1]      Bx[2,iy,iz=nz-1]     ... Bx[nx-1,iy,iz=nz-1]
ax=0 iy=2    iz=nz-1 Bx[0,iy,iz=nz-1]      Bx[1,iy,iz=nz-1]      Bx[2,iy,iz=nz-1]     ... Bx[nx-1,iy,iz=nz-1]
.
.
.
ax=0 iy=ny-1 iz=nz-1 Bx[0,iy=ny-1,iz=nz-1] Bx[1,iy=ny-1,iz=nz-1] Bx[2,iy=ny-1,iz=nz-1] ... Bx[nx-1,iy=ny-1,iz=nz-1]
### Start the By block (ax=1) with nz blocks of ny records
# first block of ny lines of nx values for iz=0
ax=1 iy=0    iz=0    By[0,iy,iz]           By[1,iy,iz]           By[2,iy,iz]           ... By[nx-1,iy,iz]
ax=1 iy=1    iz=0    By[0,iy,iz]           By[1,iy,iz]           By[2,iy,iz]           ... By[nx-1,iy,iz]
ax=1 iy=2    iz=0    By[0,iy,iz]           By[1,iy,iz]           By[2,iy,iz]           ... By[nx-1,iy,iz]
.
.
.
ax=1 iy=ny-1 iz=0    By[0,iy=ny-1,iz]      By[1,iy=ny-1,0]       By[2,iy=ny-1,iz]      ... By[nx-1,iy=ny-1,iz]
...
# last block of ny lines of nx values for iz=nz-1
ax=1 iy=0    iz=nz-1 By[0,iy,iz=nz-1]      By[1,iy,iz=nz-1]      By[2,iy,iz=nz-1]      ... By[nx-1,iy,iz=nz-1]
ax=1 iy=1    iz=nz-1 By[0,iy,iz=nz-1]      By[1,iy,iz=nz-1]      By[2,iy,iz=nz-1]      ... By[nx-1,iy,iz=nz-1]
ax=1 iy=2    iz=nz-1 By[0,iy,iz=nz-1]      By[1,iy,iz=nz-1]      By[2,iy,iz=nz-1]      ... By[nx-1,iy,iz=nz-1]
.
.
.
ax=1 iy=ny-1 iz=nz-1 By[0,iy=ny-1,iz=nz-1] By[1,iy=ny-1,iz=nz-1] By[2,iy=ny-1,iz=nz-1] ... By[nx-1,iy=ny-1,iz=nz-1]
### Start the Bz block (ax=2) with nz blocks of ny records
# first block of ny lines of nx values for iz=0
ax=2 iy=0    iz=0    Bz[0,iy,iz]           Bz[1,iy,iz]           Bz[2,iy,iz]           ... Bz[nx-1,iy,iz]
ax=2 iy=1    iz=0    Bz[0,iy,iz]           Bz[1,iy,iz]           Bz[2,iy,iz]           ... Bz[nx-1,iy,iz]
ax=2 iy=2    iz=0    Bz[0,iy,iz]           Bz[1,iy,iz]           Bz[2,iy,iz]           ... Bz[nx-1,iy,iz]
.
.
.
ax=2 iy=ny-1 iz=0    Bz[0,iy=ny-1,iz]      Bz[1,iy=ny-1,iz]      Bz[2,iy=ny-1,iz]      ... Bz[nx-1,iy=ny-1,iz]
...
# last block of ny lines of nx values for iz=nz-1
ax=2 iy=0    iz=nz-1 Bz[0,iy,iz=nz-1]      Bz[1,iy,iz=nz-1]      Bz[2,iy,iz=nz-1]      ... Bz[nx-1,iy,iz=nz-1]
ax=2 iy=1    iz=nz-1 Bz[0,iy,iz=nz-1]      Bz[1,iy,iz=nz-1]      Bz[2,iy,iz=nz-1]      ... Bz[nx-1,iy,iz=nz-1]
ax=2 iy=2    iz=nz-1 Bz[0,iy,iz=nz-1]      Bz[1,iy,iz=nz-1]      Bz[2,iy,iz=nz-1]      ... Bz[nx-1,iy,iz=nz-1]
.
.
.
ax=2 iy=ny-1 iz=nz-1 Bz[0,iy=ny-1,iz=nz-1] Bz[1,iy=ny-1,iz=nz-1] Bz[2,iy=ny-1,iz=nz-1] ... Bz[nx-1,iy=ny-1,iz=nz-1]
# end
~~~

PS: I think this note could be adapted and added in the Falaise's documentation.

**Comment by drbenmorgan** [comment]
Closing as I think @fmauger's comment fixes this, but reopen if not.
